### PR TITLE
Added QR Code Scanner Project.

### PR DESCRIPTION
**Pull request by rohit-chaware**
Project Title - QR Code Scanner

Project Description -
Web based QR code scanner created using React.js with the help of HTML5QrCodeScanner API. This application allows the user to scan any type of QR code by using vast functionality of HTML5QrCodeScanner API. User will get option to scan the QR code stored locally or they can scan QR code in realtime.

Technology Used :-
HTML5
CSS3
React.js
JavaScript
Node.js

### CODE REVIEW

**Review by rohit-chaware — COMMENTED** [review]
Project Title - QR Code Scanner

Project Description - 
Web based QR code scanner created using React.js with the help of HTML5QrCodeScanner API. This application allows the user to scan any type of QR code by using vast functionality of HTML5QrCodeScanner API. User will get option to scan the QR code stored locally or they can scan QR code in realtime. 

Technology Used :-
HTML5
CSS3
React.js
JavaScript
Node.js

**Comment by rohit-chaware** [comment]
Hello, @ayushsarode kindly review the code and take necessary action as HactoberFest is about to end.

**Comment by ayushsarode** [comment]
Thanks for your contribution!

**Comment by R4Rohit23** [comment]
Hello @ayushsarode kindly add a lable of hacktoberfest to this merge request.

**Pull request merged**
